version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: ./compose/odoo/Dockerfile
    image: docker_odoo_viniteca
    container_name: docker_odoo_viniteca
    platform: linux/amd64
    depends_on:
      - db
    # networks:
    #   - odoo
    ports:
      - '8069:8069'
    tty: true
    command: /start
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432  
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
    volumes:
      - odoo-web-data:/opt/odoo/data
      - ./extra-addons:/mnt/extra-addons
    
  db: 
    image: postgres:12.4
    # networks:
    #   - odoo
    ports:
      - "5432:5432"
    restart: always
    environment: 
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - odoo-db-data:/var/lib/postgresql/data/pgdata

  pgadmin:
      image: dpage/pgadmin4
      container_name: pgadmin4
      # networks:
      #   - odoo
      environment:
        - PGADMIN_DEFAULT_EMAIL=admin@tk-peru.com
        - PGADMIN_DEFAULT_PASSWORD=admin 
        - PGADMIN_LISTEN_PORT=80
      ports: 
        - "1234:80"
      links:
        - "db:pgsql-server"
      volumes:
        - ./pgadmin4:/var/lib/pgadmin
      restart: always        # run as a service

# networks:
#   odoo:
#     driver: bridge

volumes:
  odoo-web-data:
  odoo-db-data:

